---
- name: Add Logstash repo apt key.
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Logstash apt repo.
  apt_repository:
    repo: "deb http://packages.elastic.co/logstash/2.2/debian stable main"
    state: present

- name: Install Logstash.
  apt:
    name: logstash
    state: latest
  notify:
    - reload systemd
    - restart logstash

  # Two-pass approach. Even listing the plugins takes several seconds,
  # but it's worth it to pay that overhead rather than the several tens
  # of seconds it takes to "install" the plugin, even if it's already installed.
  # A separate action is necessary to upgrade the plugin, so simply checking
  # the plugin's presence is sufficient for idempotence.
- name: Gather list of existing Logstash plugins.
  command: /opt/logstash/bin/plugin list
  changed_when: false
  always_run: true
  register: logstash_plugin_check_result

- name: Install Logstash plugins.
  command: /opt/logstash/bin/plugin install {{ item }}
  when: item not in logstash_plugin_check_result.stdout
  with_items: elk_logstash_plugins

- name: Create Logstash config directories.
  file:
    path: "/etc/logstash/{{ item }}"
    owner: root
    group: root
    mode: "0755"
    state: directory
  with_items:
    - conf.d
    - patterns.d

- name: Copy Logstash patterns.
  template:
    src: "{{ item }}"
    dest: "/etc/logstash/patterns.d/{{ item | basename }}"
    owner: root
    group: root
    mode: "0644"
  with_fileglob:
    - logstash-patterns/*
  notify: restart logstash

- name: Copy (and verify) Logstash filters.
  template:
    src: "{{ item }}"
    # Force .conf suffix. Assumes there's a dot somewhere in the filename.
    dest: "/etc/logstash/conf.d/{{ (item | basename).split('.') | first + '.conf' }}"
    owner: root
    group: root
    mode: "0644"
    validate: "/opt/logstash/bin/logstash --configtest -f %s"
  with_fileglob:
    - logstash-configs/*
  notify: restart logstash

- name: Start logstash service.
  service:
    name: logstash
    state: running
    enabled: yes
